.. _offline-centos:

CentOS RPM Packages
===================
While CentOS and RHEL do not currently have any related Model Components [#f1]_, we have had success using `yumdownloader <https://linux.die.net/man/1/yumdownloader>`_ to download RPM packages and their dependencies.

.. seealso::

   We have found these tutorials helpful in downloading RPMs for offline use:

   * https://www.thegeekdiary.com/downloading-a-specific-version-of-package-and-its-dependencies-from-repository-for-offline-installation-using-yum/
   * https://access.redhat.com/solutions/10154


.. [#f1] We are always accepting contributions!
