# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from firewheel.lib.grpc import (
    firewheel_grpc_pb2 as firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2,
)


class FirewheelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetRepository = channel.unary_unary(
                '/firewheel_grpc.Firewheel/SetRepository',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.Repository.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.SetRepositoryResponse.FromString,
                )
        self.RemoveRepository = channel.unary_unary(
                '/firewheel_grpc.Firewheel/RemoveRepository',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.Repository.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.RemoveRepositoryResponse.FromString,
                )
        self.ListRepositories = channel.unary_stream(
                '/firewheel_grpc.Firewheel/ListRepositories',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ListRepositoriesRequest.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.Repository.FromString,
                )
        self.RemoveAllRepositories = channel.unary_unary(
                '/firewheel_grpc.Firewheel/RemoveAllRepositories',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.RemoveAllRepositoriesRequest.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.RemoveAllRepositoriesResponse.FromString,
                )
        self.GetInfo = channel.unary_unary(
                '/firewheel_grpc.Firewheel/GetInfo',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetInfoResponse.FromString,
                )
        self.GetVMMappingByUUID = channel.unary_unary(
                '/firewheel_grpc.Firewheel/GetVMMappingByUUID',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMappingUUID.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.FromString,
                )
        self.DestroyVMMappingByUUID = channel.unary_unary(
                '/firewheel_grpc.Firewheel/DestroyVMMappingByUUID',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMappingUUID.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.DestroyVMMappingResponse.FromString,
                )
        self.SetVMTimeByUUID = channel.unary_unary(
                '/firewheel_grpc.Firewheel/SetVMTimeByUUID',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.SetVMTimeByUUIDRequest.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.FromString,
                )
        self.SetVMStateByUUID = channel.unary_unary(
                '/firewheel_grpc.Firewheel/SetVMStateByUUID',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.SetVMStateByUUIDRequest.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.FromString,
                )
        self.SetVMMapping = channel.unary_unary(
                '/firewheel_grpc.Firewheel/SetVMMapping',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.FromString,
                )
        self.ListVMMappings = channel.unary_stream(
                '/firewheel_grpc.Firewheel/ListVMMappings',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ListVMMappingsRequest.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.FromString,
                )
        self.CountVMMappingsNotReady = channel.unary_unary(
                '/firewheel_grpc.Firewheel/CountVMMappingsNotReady',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.CountVMMappingsNotReadyRequest.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.CountVMMappingsNotReadyResponse.FromString,
                )
        self.DestroyAllVMMappings = channel.unary_unary(
                '/firewheel_grpc.Firewheel/DestroyAllVMMappings',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.DestroyAllVMMappingsRequest.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.DestroyAllVMMappingsResponse.FromString,
                )
        self.GetExperimentStartTime = channel.unary_unary(
                '/firewheel_grpc.Firewheel/GetExperimentStartTime',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetExperimentStartTimeRequest.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentStartTime.FromString,
                )
        self.SetExperimentStartTime = channel.unary_unary(
                '/firewheel_grpc.Firewheel/SetExperimentStartTime',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentStartTime.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentStartTime.FromString,
                )
        self.GetExperimentLaunchTime = channel.unary_unary(
                '/firewheel_grpc.Firewheel/GetExperimentLaunchTime',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetExperimentLaunchTimeRequest.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentLaunchTime.FromString,
                )
        self.SetExperimentLaunchTime = channel.unary_unary(
                '/firewheel_grpc.Firewheel/SetExperimentLaunchTime',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentLaunchTime.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentLaunchTime.FromString,
                )
        self.InitializeExperimentStartTime = channel.unary_unary(
                '/firewheel_grpc.Firewheel/InitializeExperimentStartTime',
                request_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.InitializeExperimentStartTimeRequest.SerializeToString,
                response_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.InitializeExperimentStartTimeResponse.FromString,
                )


class FirewheelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetRepository(self, request, context):
        """Set a repository.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRepository(self, request, context):
        """Remove a repository.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRepositories(self, request, context):
        """List all repositories.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAllRepositories(self, request, context):
        """Remove all repositories.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfo(self, request, context):
        """Gets the gRPC server info.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVMMappingByUUID(self, request, context):
        """Gets the vm_mapping associated with the given uuid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyVMMappingByUUID(self, request, context):
        """Destroys the vm_mapping associated with the given uuid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVMTimeByUUID(self, request, context):
        """Sets the time for the vm_mapping associated with the given uuid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVMStateByUUID(self, request, context):
        """Sets the state for the vm_mapping associated with the given uuid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVMMapping(self, request, context):
        """Sets the given vm_mapping.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVMMappings(self, request, context):
        """Iterates through all requested vm_mappings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountVMMappingsNotReady(self, request, context):
        """Returns the count of VMs that are not ready.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyAllVMMappings(self, request, context):
        """Destroys all vm_mappings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExperimentStartTime(self, request, context):
        """Gets the experiment start time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetExperimentStartTime(self, request, context):
        """Sets the experiment start time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExperimentLaunchTime(self, request, context):
        """Gets the experiment launch time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetExperimentLaunchTime(self, request, context):
        """Sets the experiment start time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeExperimentStartTime(self, request, context):
        """Initializes the experiment launch time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FirewheelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRepository,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.Repository.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.SetRepositoryResponse.SerializeToString,
            ),
            'RemoveRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRepository,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.Repository.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.RemoveRepositoryResponse.SerializeToString,
            ),
            'ListRepositories': grpc.unary_stream_rpc_method_handler(
                    servicer.ListRepositories,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ListRepositoriesRequest.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.Repository.SerializeToString,
            ),
            'RemoveAllRepositories': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAllRepositories,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.RemoveAllRepositoriesRequest.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.RemoveAllRepositoriesResponse.SerializeToString,
            ),
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetInfoRequest.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetInfoResponse.SerializeToString,
            ),
            'GetVMMappingByUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVMMappingByUUID,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMappingUUID.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.SerializeToString,
            ),
            'DestroyVMMappingByUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyVMMappingByUUID,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMappingUUID.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.DestroyVMMappingResponse.SerializeToString,
            ),
            'SetVMTimeByUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVMTimeByUUID,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.SetVMTimeByUUIDRequest.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.SerializeToString,
            ),
            'SetVMStateByUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVMStateByUUID,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.SetVMStateByUUIDRequest.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.SerializeToString,
            ),
            'SetVMMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVMMapping,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.SerializeToString,
            ),
            'ListVMMappings': grpc.unary_stream_rpc_method_handler(
                    servicer.ListVMMappings,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ListVMMappingsRequest.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.SerializeToString,
            ),
            'CountVMMappingsNotReady': grpc.unary_unary_rpc_method_handler(
                    servicer.CountVMMappingsNotReady,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.CountVMMappingsNotReadyRequest.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.CountVMMappingsNotReadyResponse.SerializeToString,
            ),
            'DestroyAllVMMappings': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyAllVMMappings,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.DestroyAllVMMappingsRequest.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.DestroyAllVMMappingsResponse.SerializeToString,
            ),
            'GetExperimentStartTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExperimentStartTime,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetExperimentStartTimeRequest.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentStartTime.SerializeToString,
            ),
            'SetExperimentStartTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExperimentStartTime,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentStartTime.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentStartTime.SerializeToString,
            ),
            'GetExperimentLaunchTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExperimentLaunchTime,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetExperimentLaunchTimeRequest.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentLaunchTime.SerializeToString,
            ),
            'SetExperimentLaunchTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExperimentLaunchTime,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentLaunchTime.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentLaunchTime.SerializeToString,
            ),
            'InitializeExperimentStartTime': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeExperimentStartTime,
                    request_deserializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.InitializeExperimentStartTimeRequest.FromString,
                    response_serializer=firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.InitializeExperimentStartTimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'firewheel_grpc.Firewheel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Firewheel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/SetRepository',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.Repository.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.SetRepositoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/RemoveRepository',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.Repository.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.RemoveRepositoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListRepositories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/firewheel_grpc.Firewheel/ListRepositories',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ListRepositoriesRequest.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.Repository.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveAllRepositories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/RemoveAllRepositories',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.RemoveAllRepositoriesRequest.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.RemoveAllRepositoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/GetInfo',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetInfoRequest.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVMMappingByUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/GetVMMappingByUUID',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMappingUUID.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyVMMappingByUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/DestroyVMMappingByUUID',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMappingUUID.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.DestroyVMMappingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVMTimeByUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/SetVMTimeByUUID',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.SetVMTimeByUUIDRequest.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVMStateByUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/SetVMStateByUUID',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.SetVMStateByUUIDRequest.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVMMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/SetVMMapping',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListVMMappings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/firewheel_grpc.Firewheel/ListVMMappings',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ListVMMappingsRequest.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.VMMapping.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CountVMMappingsNotReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/CountVMMappingsNotReady',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.CountVMMappingsNotReadyRequest.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.CountVMMappingsNotReadyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyAllVMMappings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/DestroyAllVMMappings',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.DestroyAllVMMappingsRequest.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.DestroyAllVMMappingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExperimentStartTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/GetExperimentStartTime',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetExperimentStartTimeRequest.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentStartTime.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetExperimentStartTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/SetExperimentStartTime',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentStartTime.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentStartTime.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExperimentLaunchTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/GetExperimentLaunchTime',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.GetExperimentLaunchTimeRequest.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentLaunchTime.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetExperimentLaunchTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/SetExperimentLaunchTime',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentLaunchTime.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.ExperimentLaunchTime.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitializeExperimentStartTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firewheel_grpc.Firewheel/InitializeExperimentStartTime',
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.InitializeExperimentStartTimeRequest.SerializeToString,
            firewheel_dot_lib_dot_grpc_dot_firewheel__grpc__pb2.InitializeExperimentStartTimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
