# A composite action to install discovery

name: Prepare discovery

description: Install discovery

runs:
  using: composite
  steps:
    - name: Install discovery
      run: |
        wget https://github.com/sandia-minimega/discovery/releases/download/v0.1.0/discovery.deb
        sudo dpkg -i discovery.deb
        sudo chown -R $USER:minimega /opt/discovery
      shell: bash
